module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "©𝐌𝐑 𝐌𝐀𝐍𝐔𝐋 𝐎𝐅𝐂 💚",
  "PREFIX": "*",
  "AUTO_READ_STATUS": "true",
  "MODE": "private",
  "BOT_NUMBER": "94742274855",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "false",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "false",
  "ANTI_CALL": "true ",
  "ANTI_LINK": "false",
  "ANTI_PHOTO": "warn",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": true,
  "DELETEMSGSENDTO": "",
  "ALWAYS_ONLINE": "true",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "🍂🖤𝗞𝗜𝗡𝗚 𝗔𝗡𝗝𝗔𝗡𝗔 𝗕𝗕𝗛 💦🥵🍂",
  "OWNER_NUMBER": "94750177369",
  "AUTO_BIO": "false",
  "AUTO_TYPING": "false",
  "AUTO_RECORDING": "true",
  "WARN_COUNT": "3",
};
